### PR TITLE
Fixing Map, Promise has test methods to work on iOS 8.4, fixes #37

### LINKED ISSUE #37: Feature Detection of Map on iOS 8.4
It appears our feature detection of `Map` causes a non-compliant ES version of `Map` to be detected and offloaded to:

```
Error: TypeError: Map constructor does not accept arguments at http://localhost:9000/node_modules/dojo-shim/support/has.js:69:47
  at <__intern/lib/executors/PreExecutor.js:326:32>
  at dispatcher  <__intern/browser_modules/dojo/aspect.js:66:47>
No unit test coverage for iphone 8.4 on any platform
```

We need to find a way to tighten that detection.

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug

**Description:** 

This is a fix for the Map tester failing to detect a non-compatible `Map` on iOS 8.4. The problem is that `Map` exists, but does accept take any arguments.

Once I made the error go away for this, it turns out there were some other incompatibilities, so I added another check for the `Math` library (iOS is missing the `czlr32` method) and made the `Promise` test a little bit more specific because iOS 8 supports `Promise` but not `Iterator` (which we use to pass to `Promise.all`)

**Related Issue:** #37 

Please review this checklist before submitting your PR:
- [x] There is a related issue
- [x] All contributors have signed a CLA
- [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
- [x] The code passes the CI tests
- [ ] Unit or Functional tests are included in the PR
- [x] The PR increases or maintains the overall unit test coverage percentage
- [x] The code is ready to be merged

### CODE REVIEW

File: src/support/has.ts [hunk 1]
```diff
@@ -62,10 +63,19 @@ add('es6-set', () => {
...
+		We wrap this in a try/catch because sometimes the Map constructor exists, but does not
+		take arguments (iOS 8.4)
+		 */
+		try {
+			const map = new global.Map([ [0, 1] ]);
+			return map.has(0) && typeof map.keys === 'function' &&
+				typeof map.values === 'function' && typeof map.entries === 'function';
+		}
+		catch (e) {
+			return false;
```
Comment (kitsonk) [inline src/support/has.ts:78]: Let's add Istanbul ignore here, because now we aren't running CI where this will cause issues and then it will maintain the coverage.

**Review by kitsonk — COMMENTED** [review]
One comment...

**Comment by rorticus** [comment]
I'm not really sure how to avoid the code coverage differences without the tests running on iOS...

File: src/support/has.ts (hunk 1 above)
Comment (rorticus) [reply src/support/has.ts:78]: Wow... I _just_ asked that question...

**Comment by kitsonk** [comment]
``` ts
/* istanbul ignore next: not testing on iOS at the moment */
return false;
```

😉

**Review by kitsonk — APPROVED** [review]
👍 🎃
