### PR TITLE
Fixing queue in a web worker

### LINKED ISSUE #107: XHR requests don't work in IE 11 from web worker
@rorticus commented on [Fri Apr 21 2017](https://github.com/dojo/core/issues/324)

**Bug** 

When writing the test for https://github.com/dojo/core/issues/320, I've run into another issue in IE11. It looks like XHR requests use queue, and that's causing some woe in IE 11 from a webworker. 

image

^^ that code: https://github.com/dojo/shim/blob/master/src/support/queue.ts#L65

---

@rorticus commented on [Mon Aug 14 2017](https://github.com/dojo/core/issues/324#issuecomment-322175436)

This test in dojo/shim will show the problem,

```typescript
		'queue from webworker': function (this: any) {
			if (global.Worker === undefined) {
				this.skip('does not support web workers');
				return;
			}

			const baseUrl = location.origin;
			const dfd = this.async(10000);
			const blob = new Blob([ `(function() { 
self.addEventListener('message', function (event) {
	if(event.data.baseUrl) {
		var baseUrl = event.data.baseUrl;
		importScripts(baseUrl + '/node_modules/@dojo/loader/loader.js');

		require.config({
			baseUrl: baseUrl,
			packages: [
				{ name: '@dojo', location: 'node_modules/@dojo' }
			]
		});
		
		require(['_build/src/support/queue'], function (queue) {
			queue.queueTask(function() {
				self.postMessage('success');
			});
		});
	}
});
			})()` ], { type: 'application/javascript' });
			const worker = new Worker(URL.createObjectURL(blob));
			worker.addEventListener('error', (error) => {
				dfd.reject(new Error(error.message));
			});
			worker.addEventListener('message', ({ data: result }) => {
				if (result === 'success') {
					dfd.resolve();
				}
			});

			worker.postMessage({
				baseUrl
			});
		}
```

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

The `queueTask` method is broken right now if you are running from a web worker. This is because it's using `postMessage` (since it's available) but `postMessage` doesn't work like expected (it posts to the parent window in a web worker) and the tasks never get executed.

Resolves #107

### CODE REVIEW

**Comment by rorticus** [comment]
ci failure is from the docs...

File: src/support/has.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ add('es6-weakmap', () => {
 
 /* Miscellaneous features */
 add('microtasks', () => has('es6-promise') || has('host-node') || has('dom-mutationobserver'), true);
-add('postmessage', () => typeof global.postMessage === 'function', true);
+add('postmessage', () => typeof global.window !== 'undefined' && typeof global.postMessage === 'function', true);
```
Comment (kitsonk) [inline src/support/has.ts]: Not that it is a big deal, but it would be nice to add a comment here as to why we are doing the check this way, for future generations (think of the kids!), as it is non-obvious.

File: tests/unit/support/queue.ts [hunk 2]
```diff
@@ -166,5 +167,51 @@ registerSuite({
...
+	'web workers': {
+		'queue from webworker': function (this: any) {
+			if (global.Worker === undefined) {
+				this.skip('does not support web workers');
+				return;
+			}
+
+			const baseUrl = location.origin;
+			const dfd = this.async(10000);
+			const blob = new Blob([ `(function() {
```
Comment (kitsonk) [inline tests/unit/support/queue.ts:181]: Android 4.4.4 supports WebWorkers but doesn't support [Blob creation this way](https://caniuse.com/#feat=blobbuilder).  Again, not a big deal, but maybe add a simply blob check too?

Also, this might be a good pattern for doing these tests (thank you!) and might want to consider opening an issue on test-extras to add this as some sort of helper.

Comment (rorticus) [reply tests/unit/support/queue.ts:181]: https://github.com/dojo/test-extras/issues/59

File: src/support/has.ts (hunk 1 above)
Comment (rorticus) [reply src/support/has.ts]: Added a blurb.. you know, for the children.

File: tests/unit/support/queue.ts (hunk 2 above)
Comment (rorticus) [reply tests/unit/support/queue.ts:181]: I ended up adding a simple `global.Blob === undefined` instead of a *real* Blob has check. The real Blob check is in `core` and has a few dependencies that we'd also have to copy over. Maybe that would be worth while at some point?

**Review by kitsonk — APPROVED** [review]
